export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  description: string;
  salary: string;
  type: string;
  workArrangement: string;
  requirements: string[];
  benefits: string[];
  posted: string;
  companyLogo: string;
  companyDescription: string;
  experience: string;
  connections: number;
  score: number;
  scoreLabel: string;
  timePosted: string;
  appliedStatus?: string;
  matchScore: number;
  about: string;
  jobDetails: string[];
  qualifications: {
    required: string[];
    additional: string[];
  };
  postedBy: string;
  openings: number;
  applicants: string;
  skills: string[];
  companyRating: number;
  reviewCount: string;
}

export const indianJobsData: Job[] = [
  {
    id: "1",
    title: "UX Designer",
    company: "Facebook",
    location: "New York",
    description:
      "Design user-friendly interfaces for web and mobile applications. Work closely with development teams to create intuitive user experiences.",
    salary: "₹12,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "3+ years of UX design experience",
      "Proficiency in Figma, Sketch",
      "Strong portfolio demonstrating UX skills",
      "Understanding of user research methods",
    ],
    benefits: [
      "Health insurance",
      "Flexible work hours",
      "Learning opportunities",
      "Performance bonuses",
    ],
    posted: "1d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Facebook_logo_%28square%29.png/960px-Facebook_logo_%28square%29.png",
    companyDescription: "Leading IT services and consulting company",
    experience: "5+ yrs exp",
    connections: 15,
    score: 78,
    scoreLabel: "GREAT",
    timePosted: "1d ago",
    appliedStatus: "Applied 9h ago",
    matchScore: 78,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Design user-friendly interfaces for web and mobile applications",
      "Work closely with development teams to create intuitive user experiences",
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Collaborate with product managers and engineers",
      "Ensure design consistency across all platforms",
    ],
    qualifications: {
      required: [
        "3+ years of UX design experience",
        "Proficiency in Figma, Sketch, Adobe Creative Suite",
        "Strong portfolio demonstrating UX skills",
        "Understanding of user research methods",
        "Experience with design systems and component libraries",
        "Knowledge of accessibility standards",
      ],
      additional: [
        "Experience with motion design and micro-interactions",
        "Familiarity with front-end development technologies",
        "Experience working in agile environments",
        "Strong communication and presentation skills",
      ],
    },
    postedBy: "Sarah Johnson",
    openings: 3,
    applicants: "150+",
    skills: ["UX Design", "UI Design", "Prototyping", "User Research"],
    companyRating: 4.2,
    reviewCount: "3.1k Reviews",
  },
  {
    id: "2",
    title: "Risk Analytics Consultant",
    company: "Wells Fargo",
    location: "Bengaluru",
    description:
      "Analyze financial risks and develop risk management strategies. Work with cross-functional teams to identify and mitigate potential risks.",
    salary: "Not Disclosed",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "4+ years in risk analytics",
      "Strong analytical skills",
      "Experience with risk management tools",
      "Knowledge of banking regulations",
    ],
    benefits: [
      "Competitive salary",
      "Medical benefits",
      "Career growth opportunities",
      "Work-life balance",
    ],
    posted: "4d ago",
    companyLogo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR51Y8tsBENmN-PObDKKN8cKJZqK9e65ckjbg&s",
    companyDescription: "Leading private sector bank in India",
    experience: "4+ yrs exp",
    connections: 6,
    score: 50,
    scoreLabel: "AVERAGE",
    timePosted: "4d ago",
    appliedStatus: "Applied 3d ago",
    matchScore: 50,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Analyze financial risks and develop risk management strategies",
      "Work with cross-functional teams to identify and mitigate potential risks",
      "Generate precise and comprehensive customer lists for marketing campaigns",
      "Using GUI tools to connect to multiple databases and design campaigns",
      "Building and strengthening strong business relationships with peers",
      "Consulting with partners to identify technical business requirements",
    ],
    qualifications: {
      required: [
        "4+ years in risk analytics",
        "Strong analytical skills",
        "Experience with risk management tools",
        "Knowledge of banking regulations",
        "BS/BA Degree or higher",
        "1+ Years of Work Experience",
      ],
      additional: [
        "Experience in gathering and analyzing large datasets",
        "Strong analytical skills with high attention to detail",
        "End-to-end marketing campaign management experience",
      ],
    },
    postedBy: "Jay Patel",
    openings: 4,
    applicants: "100+",
    skills: [
      "Risk Analytics",
      "Financial Modeling",
      "Data Analysis",
      "Banking",
    ],
    companyRating: 4.1,
    reviewCount: "2.8k Reviews",
  },
  {
    id: "3",
    title: "Senior Software Engineer",
    company: "Infosys",
    location: "Hyderabad",
    description:
      "Develop and maintain enterprise software solutions. Lead technical initiatives and mentor junior developers.",
    salary: "₹15,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "5+ years of software development",
      "Strong in Java, Python, or .NET",
      "Experience with cloud platforms",
      "Leadership skills",
    ],
    benefits: [
      "Comprehensive health coverage",
      "Stock options",
      "Professional development",
      "Flexible working",
    ],
    posted: "2d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/2560px-Infosys_logo.svg.png",
    companyDescription: "Global leader in consulting and digital services",
    experience: "5+ yrs exp",
    connections: 22,
    score: 85,
    scoreLabel: "GREAT",
    timePosted: "2d ago",
    matchScore: 85,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Develop and maintain enterprise software solutions",
      "Lead technical initiatives and mentor junior developers",
      "Design and implement scalable software architectures",
      "Collaborate with cross-functional teams on project delivery",
      "Perform code reviews and ensure code quality standards",
      "Troubleshoot and resolve complex technical issues",
    ],
    qualifications: {
      required: [
        "5+ years of software development",
        "Strong in Java, Python, or .NET",
        "Experience with cloud platforms",
        "Leadership skills",
        "BS/BA Degree in Computer Science",
        "Experience with microservices architecture",
      ],
      additional: [
        "Experience with containerization technologies",
        "Knowledge of CI/CD pipelines",
        "Understanding of database design principles",
      ],
    },
    postedBy: "Rahul Sharma",
    openings: 2,
    applicants: "200+",
    skills: ["Java", "Python", "Cloud Computing", "Leadership"],
    companyRating: 4.3,
    reviewCount: "4.2k Reviews",
  },
  {
    id: "4",
    title: "Product Manager",
    company: "Flipkart",
    location: "Bangalore",
    description:
      "Drive product strategy and roadmap for e-commerce platform. Collaborate with engineering and design teams to deliver innovative features.",
    salary: "₹25,00,000",
    type: "Full-time",
    workArrangement: "Remote",
    requirements: [
      "6+ years in product management",
      "Experience in e-commerce",
      "Strong analytical skills",
      "MBA preferred",
    ],
    benefits: [
      "Competitive compensation",
      "Employee stock options",
      "Health and wellness programs",
      "Learning and development",
    ],
    posted: "3d ago",
    companyLogo:
      "https://images.icon-icons.com/729/PNG/512/flipkart_icon-icons.com_62718.png",
    companyDescription: "India's leading e-commerce marketplace",
    experience: "6+ yrs exp",
    connections: 18,
    score: 92,
    scoreLabel: "GREAT",
    timePosted: "3d ago",
    matchScore: 92,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Drive product strategy and roadmap for e-commerce platform",
      "Collaborate with engineering and design teams to deliver innovative features",
      "Analyze market trends and competitive landscape",
      "Define product requirements and user stories",
      "Work with data analytics to make informed product decisions",
      "Coordinate with marketing and sales teams for product launches",
    ],
    qualifications: {
      required: [
        "6+ years in product management",
        "Experience in e-commerce",
        "Strong analytical skills",
        "MBA preferred",
        "Experience with agile methodologies",
        "Strong stakeholder management skills",
      ],
      additional: [
        "Experience with A/B testing and user research",
        "Knowledge of e-commerce platforms and technologies",
        "Understanding of customer journey mapping",
      ],
    },
    postedBy: "Priya Verma",
    openings: 1,
    applicants: "300+",
    skills: ["Product Management", "E-commerce", "Analytics", "Strategy"],
    companyRating: 4.5,
    reviewCount: "5.1k Reviews",
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "Wipro",
    location: "Pune",
    description:
      "Apply machine learning and statistical analysis to solve business problems. Work with large datasets to derive actionable insights.",
    salary: "₹18,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "4+ years in data science",
      "Strong in Python, R, SQL",
      "Experience with ML frameworks",
      "Statistical analysis expertise",
    ],
    benefits: [
      "Health insurance",
      "Performance bonuses",
      "Learning opportunities",
      "Work from home options",
    ],
    posted: "1d ago",
    companyLogo:
      "https://cdn.imgbin.com/10/5/4/imgbin-wipro-logo-business-corporate-identity-business-AFcP5VFky8aXTCiHugTnXHHug.jpg",
    companyDescription: "Leading technology services company",
    experience: "4+ yrs exp",
    connections: 12,
    score: 68,
    scoreLabel: "AVERAGE",
    timePosted: "1d ago",
    matchScore: 68,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Apply machine learning and statistical analysis to solve business problems",
      "Work with large datasets to derive actionable insights",
      "Develop predictive models and algorithms",
      "Collaborate with business teams to understand requirements",
      "Present findings and recommendations to stakeholders",
      "Maintain and improve existing ML models",
    ],
    qualifications: {
      required: [
        "4+ years in data science",
        "Strong in Python, R, SQL",
        "Experience with ML frameworks",
        "Statistical analysis expertise",
        "MS/PhD in Statistics, Mathematics, or related field",
        "Experience with big data technologies",
      ],
      additional: [
        "Experience with deep learning frameworks",
        "Knowledge of cloud-based ML platforms",
        "Understanding of MLOps practices",
      ],
    },
    postedBy: "Amit Kumar",
    openings: 5,
    applicants: "180+",
    skills: ["Machine Learning", "Python", "R", "SQL", "Statistics"],
    companyRating: 4.0,
    reviewCount: "3.5k Reviews",
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "Tech Mahindra",
    location: "Chennai",
    description:
      "Manage cloud infrastructure and CI/CD pipelines. Ensure system reliability and optimize deployment processes.",
    salary: "₹16,00,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "3+ years in DevOps",
      "Experience with AWS/Azure",
      "Knowledge of Docker, Kubernetes",
      "Scripting skills",
    ],
    benefits: [
      "Medical coverage",
      "Flexible hours",
      "Skill development programs",
      "Performance incentives",
    ],
    posted: "5d ago",
    companyLogo:
      "https://insights.techmahindra.com/styles/brand_kit_image/s3/images/techmslides_logo.png",
    companyDescription: "Digital transformation and technology services",
    experience: "3+ yrs exp",
    connections: 8,
    score: 72,
    scoreLabel: "GREAT",
    timePosted: "5d ago",
    matchScore: 72,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Manage cloud infrastructure and CI/CD pipelines",
      "Ensure system reliability and optimize deployment processes",
      "Automate infrastructure provisioning and configuration",
      "Monitor system performance and implement improvements",
      "Collaborate with development teams for deployment strategies",
      "Maintain security standards and compliance requirements",
    ],
    qualifications: {
      required: [
        "3+ years in DevOps",
        "Experience with AWS/Azure",
        "Knowledge of Docker, Kubernetes",
        "Scripting skills",
        "BS/BA in Computer Science or related field",
        "Experience with infrastructure as code",
      ],
      additional: [
        "Experience with monitoring and logging tools",
        "Knowledge of security best practices",
        "Understanding of microservices architecture",
      ],
    },
    postedBy: "Suresh Reddy",
    openings: 3,
    applicants: "120+",
    skills: ["DevOps", "AWS", "Docker", "Kubernetes", "CI/CD"],
    companyRating: 4.2,
    reviewCount: "2.9k Reviews",
  },
  {
    id: "7",
    title: "Frontend Developer",
    company: "Zomato",
    location: "Gurgaon",
    description:
      "Build responsive web applications using modern JavaScript frameworks. Focus on user experience and performance optimization.",
    salary: "₹14,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "3+ years in frontend development",
      "Strong in React, Vue.js",
      "Experience with responsive design",
      "Knowledge of modern build tools",
    ],
    benefits: [
      "Food allowance",
      "Health insurance",
      "Flexible working hours",
      "Learning budget",
    ],
    posted: "2d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Zomato_logo.png/960px-Zomato_logo.png",
    companyDescription: "Leading food delivery and restaurant platform",
    experience: "3+ yrs exp",
    connections: 14,
    score: 76,
    scoreLabel: "GREAT",
    timePosted: "2d ago",
    matchScore: 76,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Build responsive web applications using modern JavaScript frameworks",
      "Focus on user experience and performance optimization",
      "Collaborate with designers to implement UI/UX designs",
      "Write clean, maintainable, and well-documented code",
      "Participate in code reviews and technical discussions",
      "Stay updated with latest frontend technologies and best practices",
    ],
    qualifications: {
      required: [
        "3+ years in frontend development",
        "Strong in React, Vue.js",
        "Experience with responsive design",
        "Knowledge of modern build tools",
        "BS/BA in Computer Science or related field",
        "Experience with state management libraries",
      ],
      additional: [
        "Experience with TypeScript and modern CSS",
        "Knowledge of testing frameworks",
        "Understanding of accessibility standards",
      ],
    },
    postedBy: "Neha Singh",
    openings: 4,
    applicants: "250+",
    skills: ["React", "Vue.js", "JavaScript", "CSS", "Frontend Development"],
    companyRating: 4.4,
    reviewCount: "3.8k Reviews",
  },
  {
    id: "8",
    title: "Business Analyst",
    company: "Accenture",
    location: "Delhi",
    description:
      "Analyze business processes and requirements. Work with stakeholders to design and implement business solutions.",
    salary: "₹11,00,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "2+ years in business analysis",
      "Strong analytical skills",
      "Experience with requirement gathering",
      "Knowledge of business process modeling",
    ],
    benefits: [
      "Global exposure",
      "Training programs",
      "Health benefits",
      "Career progression",
    ],
    posted: "6d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/1280px-Accenture.svg.png",
    companyDescription: "Global professional services company",
    experience: "2+ yrs exp",
    connections: 10,
    score: 64,
    scoreLabel: "AVERAGE",
    timePosted: "6d ago",
    matchScore: 64,
    about:
      "You will help us deliver on our vision and build strong relationships with Enterprise partners. You will also have the opportunity to demonstrate leadership through contributing to a company culture that supports customers in achieving their financial goals, team members in developing their careers, and communities in continuing to thrive.",
    jobDetails: [
      "Analyze business processes and requirements",
      "Work with stakeholders to design and implement business solutions",
      "Gather and document functional and non-functional requirements",
      "Create process flow diagrams and business requirement documents",
      "Facilitate workshops and stakeholder meetings",
      "Support testing and implementation of business solutions",
    ],
    qualifications: {
      required: [
        "2+ years in business analysis",
        "Strong analytical skills",
        "Experience with requirement gathering",
        "Knowledge of business process modeling",
        "BS/BA in Business Administration or related field",
        "Experience with business analysis tools",
      ],
      additional: [
        "Experience with agile methodologies",
        "Knowledge of data analysis and reporting",
        "Understanding of change management principles",
      ],
    },
    postedBy: "Rajesh Malhotra",
    openings: 2,
    applicants: "90+",
    skills: [
      "Business Analysis",
      "Requirements Gathering",
      "Process Modeling",
      "Stakeholder Management",
    ],
    companyRating: 4.1,
    reviewCount: "4.5k Reviews",
  },
  {
    id: "9",
    title: "Digital Marketing Manager",
    company: "Paytm",
    location: "Noida",
    description:
      "Lead digital marketing campaigns and strategies. Manage social media presence and optimize conversion rates across digital channels.",
    salary: "₹13,50,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "4+ years in digital marketing",
      "Experience with Google Ads, Facebook Ads",
      "Strong analytical skills",
      "Knowledge of SEO/SEM",
    ],
    benefits: [
      "Performance bonuses",
      "Health insurance",
      "Professional development",
      "Flexible work schedule",
    ],
    posted: "1d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Paytm_Logo_%28standalone%29.svg/1024px-Paytm_Logo_%28standalone%29.svg.png",
    companyDescription: "Leading digital payments and financial services",
    experience: "4+ yrs exp",
    connections: 19,
    score: 81,
    scoreLabel: "GREAT",
    timePosted: "1d ago",
    matchScore: 81,
    about:
      "Join our marketing team to drive customer acquisition and brand awareness. You'll work with cutting-edge marketing technologies and data analytics to create impactful campaigns that reach millions of users.",
    jobDetails: [
      "Lead digital marketing campaigns and strategies",
      "Manage social media presence and optimize conversion rates",
      "Analyze campaign performance and ROI metrics",
      "Collaborate with creative teams for content development",
      "Implement A/B testing for marketing initiatives",
      "Stay updated with latest digital marketing trends",
    ],
    qualifications: {
      required: [
        "4+ years in digital marketing",
        "Experience with Google Ads, Facebook Ads",
        "Strong analytical skills",
        "Knowledge of SEO/SEM",
        "MBA in Marketing preferred",
        "Experience with marketing automation tools",
      ],
      additional: [
        "Experience with content marketing and influencer partnerships",
        "Knowledge of email marketing platforms",
        "Understanding of e-commerce marketing strategies",
      ],
    },
    postedBy: "Ankita Sharma",
    openings: 2,
    applicants: "175+",
    skills: [
      "Digital Marketing",
      "SEO",
      "Google Ads",
      "Analytics",
      "Social Media",
    ],
    companyRating: 4.3,
    reviewCount: "2.7k Reviews",
  },
  {
    id: "10",
    title: "Mobile App Developer",
    company: "Swiggy",
    location: "Bangalore",
    description:
      "Develop native mobile applications for iOS and Android platforms. Work on features that serve millions of food delivery customers.",
    salary: "₹17,00,000",
    type: "Full-time",
    workArrangement: "Remote",
    requirements: [
      "3+ years in mobile development",
      "Strong in React Native or Flutter",
      "Experience with native iOS/Android",
      "Knowledge of mobile UI/UX principles",
    ],
    benefits: [
      "Free meal credits",
      "Stock options",
      "Remote work flexibility",
      "Learning opportunities",
    ],
    posted: "3d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/1024px-Swiggy_logo.svg.png",
    companyDescription: "India's leading on-demand convenience platform",
    experience: "3+ yrs exp",
    connections: 16,
    score: 88,
    scoreLabel: "GREAT",
    timePosted: "3d ago",
    matchScore: 88,
    about:
      "Be part of a team that's revolutionizing food delivery in India. You'll work on high-impact features that directly affect customer experience and business growth.",
    jobDetails: [
      "Develop native mobile applications for iOS and Android platforms",
      "Work on features that serve millions of food delivery customers",
      "Optimize app performance and user experience",
      "Collaborate with backend teams for API integration",
      "Implement real-time tracking and notification features",
      "Ensure code quality through testing and code reviews",
    ],
    qualifications: {
      required: [
        "3+ years in mobile development",
        "Strong in React Native or Flutter",
        "Experience with native iOS/Android",
        "Knowledge of mobile UI/UX principles",
        "BS in Computer Science or related field",
        "Experience with RESTful APIs and third-party integrations",
      ],
      additional: [
        "Experience with mobile app testing frameworks",
        "Knowledge of app store submission processes",
        "Understanding of mobile security best practices",
      ],
    },
    postedBy: "Vikram Patel",
    openings: 3,
    applicants: "220+",
    skills: ["React Native", "Flutter", "iOS", "Android", "Mobile Development"],
    companyRating: 4.6,
    reviewCount: "3.2k Reviews",
  },
  {
    id: "11",
    title: "Cybersecurity Analyst",
    company: "TCS",
    location: "Mumbai",
    description:
      "Monitor and analyze security threats. Implement security measures and respond to cybersecurity incidents across enterprise systems.",
    salary: "₹12,50,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "3+ years in cybersecurity",
      "Knowledge of security frameworks",
      "Experience with SIEM tools",
      "Understanding of network security",
    ],
    benefits: [
      "Security clearance support",
      "Certification reimbursement",
      "Health benefits",
      "Career advancement",
    ],
    posted: "4d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Tata_Consultancy_Services_Logo.svg/1024px-Tata_Consultancy_Services_Logo.svg.png",
    companyDescription: "Leading global IT services and consulting company",
    experience: "3+ yrs exp",
    connections: 11,
    score: 74,
    scoreLabel: "GREAT",
    timePosted: "4d ago",
    matchScore: 74,
    about:
      "Join our cybersecurity team to protect critical infrastructure and sensitive data. You'll work with cutting-edge security technologies and help shape security policies for enterprise clients.",
    jobDetails: [
      "Monitor and analyze security threats",
      "Implement security measures and respond to cybersecurity incidents",
      "Conduct vulnerability assessments and penetration testing",
      "Develop security policies and procedures",
      "Investigate security breaches and incidents",
      "Provide security awareness training to teams",
    ],
    qualifications: {
      required: [
        "3+ years in cybersecurity",
        "Knowledge of security frameworks (NIST, ISO 27001)",
        "Experience with SIEM tools",
        "Understanding of network security",
        "BS in Computer Science or Cybersecurity",
        "Industry certifications (CISSP, CEH, or similar)",
      ],
      additional: [
        "Experience with cloud security (AWS, Azure)",
        "Knowledge of compliance requirements (GDPR, SOX)",
        "Understanding of threat intelligence platforms",
      ],
    },
    postedBy: "Arjun Nair",
    openings: 4,
    applicants: "140+",
    skills: [
      "Cybersecurity",
      "SIEM",
      "Penetration Testing",
      "Network Security",
      "Incident Response",
    ],
    companyRating: 4.2,
    reviewCount: "5.8k Reviews",
  },
  {
    id: "12",
    title: "Machine Learning Engineer",
    company: "Ola",
    location: "Bangalore",
    description:
      "Build and deploy ML models for ride-sharing optimization. Work on algorithms that power pricing, demand forecasting, and route optimization.",
    salary: "₹22,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "4+ years in machine learning",
      "Strong in Python, TensorFlow/PyTorch",
      "Experience with MLOps",
      "Knowledge of distributed computing",
    ],
    benefits: [
      "Free ride credits",
      "Stock options",
      "Flexible hours",
      "Research opportunities",
    ],
    posted: "2d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Ola_Cabs_logo.png/1024px-Ola_Cabs_logo.png",
    companyDescription: "India's largest mobility platform",
    experience: "4+ yrs exp",
    connections: 21,
    score: 89,
    scoreLabel: "EXCELLENT",
    timePosted: "2d ago",
    matchScore: 89,
    about:
      "Shape the future of mobility through advanced machine learning. You'll work on complex algorithms that optimize transportation for millions of users across India.",
    jobDetails: [
      "Build and deploy ML models for ride-sharing optimization",
      "Work on algorithms that power pricing, demand forecasting, and route optimization",
      "Develop real-time recommendation systems",
      "Optimize model performance and scalability",
      "Collaborate with data engineering teams",
      "Research and implement state-of-the-art ML techniques",
    ],
    qualifications: {
      required: [
        "4+ years in machine learning",
        "Strong in Python, TensorFlow/PyTorch",
        "Experience with MLOps and model deployment",
        "Knowledge of distributed computing",
        "MS/PhD in Computer Science or related field",
        "Experience with cloud platforms (AWS/GCP)",
      ],
      additional: [
        "Experience with real-time streaming data",
        "Knowledge of reinforcement learning",
        "Understanding of A/B testing for ML models",
      ],
    },
    postedBy: "Deepak Singh",
    openings: 2,
    applicants: "280+",
    skills: [
      "Machine Learning",
      "Python",
      "TensorFlow",
      "MLOps",
      "Distributed Computing",
    ],
    companyRating: 4.4,
    reviewCount: "2.1k Reviews",
  },
  {
    id: "13",
    title: "Quality Assurance Engineer",
    company: "Cognizant",
    location: "Chennai",
    description:
      "Design and execute test strategies for enterprise applications. Ensure software quality through automated and manual testing processes.",
    salary: "₹9,50,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "3+ years in QA testing",
      "Experience with automation tools",
      "Knowledge of testing methodologies",
      "Strong analytical skills",
    ],
    benefits: [
      "Health insurance",
      "Training programs",
      "Career development",
      "Work-life balance",
    ],
    posted: "5d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Cognizant_logo_2022.svg/1024px-Cognizant_logo_2022.svg.png",
    companyDescription:
      "Professional services company focused on digital transformation",
    experience: "3+ yrs exp",
    connections: 9,
    score: 71,
    scoreLabel: "GREAT",
    timePosted: "5d ago",
    matchScore: 71,
    about:
      "Ensure the highest quality standards for our clients' critical applications. You'll work with diverse technologies and contribute to improving software development processes.",
    jobDetails: [
      "Design and execute test strategies for enterprise applications",
      "Ensure software quality through automated and manual testing processes",
      "Create comprehensive test plans and test cases",
      "Identify, document, and track software defects",
      "Collaborate with development teams for bug resolution",
      "Implement test automation frameworks",
    ],
    qualifications: {
      required: [
        "3+ years in QA testing",
        "Experience with automation tools (Selenium, TestNG)",
        "Knowledge of testing methodologies",
        "Strong analytical skills",
        "BS in Computer Science or related field",
        "Experience with bug tracking tools",
      ],
      additional: [
        "Experience with API testing tools",
        "Knowledge of performance testing",
        "Understanding of CI/CD pipelines",
      ],
    },
    postedBy: "Sunita Reddy",
    openings: 6,
    applicants: "160+",
    skills: [
      "QA Testing",
      "Selenium",
      "Test Automation",
      "Manual Testing",
      "Bug Tracking",
    ],
    companyRating: 4.0,
    reviewCount: "4.1k Reviews",
  },
  {
    id: "14",
    title: "Cloud Solutions Architect",
    company: "Amazon Web Services",
    location: "Hyderabad",
    description:
      "Design cloud architectures for enterprise clients. Lead cloud migration projects and provide technical guidance on AWS services.",
    salary: "₹28,00,000",
    type: "Full-time",
    workArrangement: "Hybrid",
    requirements: [
      "5+ years in cloud computing",
      "AWS certifications required",
      "Experience with microservices",
      "Strong communication skills",
    ],
    benefits: [
      "AWS credits and training",
      "Stock purchase plan",
      "Comprehensive benefits",
      "Global opportunities",
    ],
    posted: "1d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1024px-Amazon_Web_Services_Logo.svg.png",
    companyDescription: "World's most comprehensive cloud platform",
    experience: "5+ yrs exp",
    connections: 28,
    score: 94,
    scoreLabel: "EXCELLENT",
    timePosted: "1d ago",
    matchScore: 94,
    about:
      "Help organizations transform their businesses through cloud adoption. You'll work with cutting-edge technologies and guide clients through their digital transformation journey.",
    jobDetails: [
      "Design cloud architectures for enterprise clients",
      "Lead cloud migration projects and provide technical guidance",
      "Conduct architecture reviews and assessments",
      "Create technical documentation and best practices",
      "Mentor junior architects and engineers",
      "Stay current with latest AWS services and features",
    ],
    qualifications: {
      required: [
        "5+ years in cloud computing",
        "AWS certifications (Solutions Architect Professional)",
        "Experience with microservices architecture",
        "Strong communication and presentation skills",
        "BS in Computer Science or related field",
        "Experience with infrastructure as code",
      ],
      additional: [
        "Experience with multiple cloud platforms",
        "Knowledge of containerization and orchestration",
        "Understanding of security and compliance frameworks",
      ],
    },
    postedBy: "Ravi Krishnan",
    openings: 3,
    applicants: "320+",
    skills: [
      "AWS",
      "Cloud Architecture",
      "Microservices",
      "DevOps",
      "Infrastructure as Code",
    ],
    companyRating: 4.7,
    reviewCount: "1.2k Reviews",
  },
  {
    id: "15",
    title: "HR Business Partner",
    company: "Unilever",
    location: "Mumbai",
    description:
      "Partner with business leaders to drive HR strategy and initiatives. Focus on talent management, employee engagement, and organizational development.",
    salary: "₹15,50,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "5+ years in HR roles",
      "Experience in talent management",
      "Strong interpersonal skills",
      "MBA in HR preferred",
    ],
    benefits: [
      "Global career opportunities",
      "Learning and development",
      "Health and wellness programs",
      "Employee discounts",
    ],
    posted: "3d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Unilever.svg/1024px-Unilever.svg.png",
    companyDescription: "Leading consumer goods company with global presence",
    experience: "5+ yrs exp",
    connections: 13,
    score: 79,
    scoreLabel: "GREAT",
    timePosted: "3d ago",
    matchScore: 79,
    about:
      "Shape the employee experience and drive organizational success. You'll work with diverse teams and contribute to building a high-performance culture that drives business results.",
    jobDetails: [
      "Partner with business leaders to drive HR strategy and initiatives",
      "Focus on talent management, employee engagement, and organizational development",
      "Lead recruitment and onboarding processes",
      "Develop and implement employee development programs",
      "Handle employee relations and performance management",
      "Support change management initiatives",
    ],
    qualifications: {
      required: [
        "5+ years in HR roles",
        "Experience in talent management and employee relations",
        "Strong interpersonal and communication skills",
        "MBA in HR or related field preferred",
        "Knowledge of employment laws and regulations",
        "Experience with HR information systems",
      ],
      additional: [
        "Experience in multinational organizations",
        "Knowledge of diversity and inclusion best practices",
        "Understanding of organizational psychology",
      ],
    },
    postedBy: "Meera Joshi",
    openings: 2,
    applicants: "110+",
    skills: [
      "HR Strategy",
      "Talent Management",
      "Employee Relations",
      "Organizational Development",
      "Change Management",
    ],
    companyRating: 4.5,
    reviewCount: "1.8k Reviews",
  },
  {
    id: "16",
    title: "Financial Analyst",
    company: "HDFC Bank",
    location: "Mumbai",
    description:
      "Analyze financial data and market trends. Prepare financial reports and support investment decision-making processes.",
    salary: "₹10,50,000",
    type: "Full-time",
    workArrangement: "From Office",
    requirements: [
      "3+ years in financial analysis",
      "Strong Excel and modeling skills",
      "Knowledge of financial markets",
      "CFA or MBA Finance preferred",
    ],
    benefits: [
      "Performance bonuses",
      "Banking benefits",
      "Health insurance",
      "Career progression",
    ],
    posted: "4d ago",
    companyLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/HDFC_Bank_Logo.svg/1024px-HDFC_Bank_Logo.svg.png",
    companyDescription: "India's largest private sector bank",
    experience: "3+ yrs exp",
    connections: 17,
    score: 67,
    scoreLabel: "AVERAGE",
    timePosted: "4d ago",
    matchScore: 67,
    about:
      "Play a key role in financial planning and analysis for one of India's leading banks. You'll work with large datasets and contribute to strategic decision-making processes.",
    jobDetails: [
      "Analyze financial data and market trends",
      "Prepare financial reports and support investment decision-making",
      "Develop financial models and forecasts",
      "Monitor key performance indicators",
      "Collaborate with various departments for budget planning",
      "Present findings to senior management",
    ],
    qualifications: {
      required: [
        "3+ years in financial analysis",
        "Strong Excel and financial modeling skills",
        "Knowledge of financial markets and banking",
        "CFA or MBA Finance preferred",
        "Bachelor's degree in Finance or Economics",
        "Experience with financial software and databases",
      ],
      additional: [
        "Experience with regulatory reporting",
        "Knowledge of risk management principles",
        "Understanding of credit analysis",
      ],
    },
    postedBy: "Sanjay Gupta",
    openings: 4,
    applicants: "190+",
    skills: [
      "Financial Analysis",
      "Excel",
      "Financial Modeling",
      "Banking",
      "Risk Assessment",
    ],
    companyRating: 4.3,
    reviewCount: "6.2k Reviews",
  },
];
